### PR TITLE
feat(web worker): add init options #322

### PR DESCRIPTION
**Pull request by binvb**
reference https://github.com/josdejong/workerpool/issues/322

### CODE REVIEW

**Comment by binvb** [comment]
oop, still need disting options

**Comment by josdejong** [comment]
Thanks for your PR @binvb , this will be a useful extension! Sorry for my late reply.

I think the PR needs a bit of refinement. Feedbacks:

1. I think that the code of `resolveBrowserOptions` can be simplified a bit, it loops over all keys of `opts` and for each key it searches the array `workderOptArr`. Instead, you can loop over `workderOptArr` and copy the property when it is defined.
2. can you document the new options in the readme?
3. it would be nice to unit test this behavior, but I'm not sure how to do that for real since we don't have a test setup that can run in the browser. Do you have any ideas? At least it is possible to validate that only the three allowed options are copied and passed to setupBrowserWorker via setupWorker. Maybe it's also interesting to create a minimal  [example](https://github.com/josdejong/workerpool/tree/master/examples/browser) demonstrating the behavior so we can at least manually validate that it works for real. What do you think?

**Comment by josdejong** [comment]
I was just thinking: it is probably a good idea to not pick these three properties from the generic `options` object (which contains options for the workerpool), but create a separate, nested object just like `forkArgs` and `forkOpts` (for nodejs processes). That way, we don't have to pick the properties but can pass the whole object as-is and won't mix these two different "levels" of options.

**Comment by josdejong** [comment]
@binvb are you still interested in getting this PR finished? It would be a useful addition. 

If not, is anyone else interested in helping out here?

**Comment by DonatJR** [comment]
@josdejong I would be interested in getting this finished. Are you okay with me creating a new pull request once I have the changes ready?

**Comment by josdejong** [comment]
Thanks @DonatJR , a new PR would be very welcome!

**Comment by josdejong** [comment]
Closing this PR now in favor of #400, which is published now in `v6.5.0`.

**Pull request closed without merging**
