### PR TITLE
fix: missing workerThreadOpts on terminate worker

### PR DESCRIPTION
**Pull request by Michsior14**
Adds missing workerThreadOpts on terminate hooks.

### CODE REVIEW

**Comment by Michsior14** [comment]
@josdejong Any review ETA?

**Comment by josdejong** [comment]
@Michsior14 I plan to review your 3 PR's tomorrow.

**Comment by josdejong** [comment]
Looks good, thanks for this improvement Michał!

**Comment by josdejong** [comment]
@Michsior14 when do you expect to be able to finish #377 and #374? If that is soon I'll wait publishing to npm until those two PR's are merged too.

**Comment by Michsior14** [comment]
> @Michsior14 when do you expect to be able to finish #377 and #374? If that is soon I'll wait publishing to npm until those two PR's are merged too.

Today or during weekend ;)

**Comment by josdejong** [comment]
💪

**Comment by josdejong** [comment]
Published now in `v6.4.0`, thanks again, this is quite a major release :)

**Pull request merged**
