### PR TITLE
Allow forkOpts to be computed dynamically

### PR DESCRIPTION
**Pull request by forty**
Hello, 

I added this to be able use cases where I needed to attributed some unique identifiers to all workers in the pool.

What do you think?

### CODE REVIEW

**Comment by forty** [comment]
I see that my test fails on the CI, but it fine locally, any idea what the issue might be?

**Comment by josdejong** [comment]
Thanks Quentin for your PR. I've run your PR locally, all unit tests pass there too. I'm not sure why they are failing on the CI.

Can you explain your use case? Why do you need to know an unique id of every worker?

Related PR: #225

**Comment by forty** [comment]
My very specific use case would be to be able to assign unique database to mocha worker processes, but I assume there could be other use cases.

The person who originally open the case wanted to assign unique port (though in that case, there probably other ways) https://github.com/mochajs/mocha/issues/4456#issue-713152909

More details:
- my comment on the same case detailing my use case https://github.com/mochajs/mocha/issues/4456#issuecomment-844924184
- a draft PR for the same user that opened the issue to solve the problem in mocha only https://github.com/mochajs/mocha/pull/4463/files (which is pretty clever if that indeed works, but is also an awful hack :grimacing: )

**Comment by forty** [comment]
@josdejong what do you think of the use case? would you merge that PR? If yes, I can take some time to investigate the CI issue.

**Comment by josdejong** [comment]
Sorry for the delay @forty. 

This use case makes sense indeed, so good to build a solution for it, thanks 👍 

Thinking aloud here: instead of passing dynamic options to a worker, wouldn't it make more sense to implement life cycle hooks for workers? So inside the worker you get two two methods `create` and `destroy`, and you can do initialization and cleanup work when needed, and from the workerpool you can keep track on created/destroyed workers, pass dynamic options via the create function. So in your case case when having a `destroy` function you could re-claim a "unique database" again after a worker did shutdown or crash.

**Comment by forty** [comment]
@josdejong hi, I'm back :) I tried to put together something along the lines of you suggestions. It allows to release resources when the worker is terminated. Let me know if you like it, I'm happy to continue improving the PR if it's going in the right direction.

Thanks!

**Comment by forty** [comment]
(in particular I know it's missing documentation and I'll update the typings)

**Comment by josdejong** [comment]
@forty thanks for your updates. And sorry for my very late reply, I wasn't able to work much on my open source projects last months.

I really like where your PR is heading!! 😎 . I personally would rename `onWorkerCreation` and `onWorkerTermination` to `onCreateWorker` and `onTerminateWorker`, but if you like the current names better it is fine with me.

Indeed documentation and typings are missing, but besides that the PR looks ready to merge 👍

**Comment by forty** [comment]
@josdejong no worries, thanks for getting back to me!

I didn't have strong feelings on the naming and like your proposal, so I made the update.

I added types and doc now, please let me know if that looks good. Thanks!

**Comment by josdejong** [comment]
Wow that's fast 🚀 😄 , thanks, looks good indeed.

Before clicking the merge button, I would love hear if you have any thoughts on #329, which is related but about passing options to a worker in the browser. Do you have any ideas on how we could unify this @forty ? (or maybe we don't have to).

**Comment by forty** [comment]
I think it would make sense to expose those new properties
1- in the pool options
and then
2- in the create/terminate Worker callbacks so they can be overriden as well for each worker

It should be an easy change once both PRs are merged.

**Comment by josdejong** [comment]
That would be very flexible indeed. Ok let's first merge this PR and go from there. 

I see the CI tests are not running well for unclear reason (locally all tests work fine for me). I don't have time today but will look into it asap

**Comment by forty** [comment]
I have rebased to latest master to get the GH workflow config, and I tested locally with this tool https://github.com/nektos/act, and I had no issue.
I'm not sure what to think :thinking:

**Comment by forty** [comment]
@josdejong Found & fixed the issue :) 

(1) On GH, because the number of CPU is low, the default maxWorker is 1, which means that no parallelism happens.
Forcing it to a high enough number fixes the problem.

(2) The infinite loading is because the terminate function was never call in case a previous assert fails. Calling it in case of error fixes the problem.

Both problems could affect other tests. The second one is just annoying, but the first one could hide problems as many tests actually run with a single worker and no parallelism, it's possible that we could have tests failing locally and succeeding on GH.

Anyway, it should be all good now :+1:

**Comment by josdejong** [comment]
Just wow. That makes sense, but what a tricky case! 

It would be nice if we could make sure the terminate function is always called, also in case of a failed assertion (like with `.finally(...)` in a promise). I'm not sure though if it is worth the trouble (I mean, normally the tests succeed and when one test fails and hangs, it's a good enough indication to have a look at that failed test).

Will merge your PR now, thanks again.

**Comment by josdejong** [comment]
I added a usage example to the examples section: 5837a9cea3c320f28839b3f4de258c5be54b8c42, and have now published the new features in `v6.2.0` 🎉 .

**Comment by forty** [comment]
Thanks!

Regarding the terminate pool in tests I also tried to think a bit how it could be done in a more consistent way.

What I think could work well would be to move the "var pool" one level higher and always re-use that same var. This way we could add a pool.terminate in a afterEach hook.

**Comment by josdejong** [comment]
Ah, that makes a lot of sense, I think that will work for most (or all) tests!

**Pull request merged**
