### PR TITLE
Add Extra functionality to the pool

### PR DESCRIPTION
**Pull request by JPig**
- Added extra option to pool constructor to allow disabling `autoStart`
- Added ability to `pause` workerpool
- Added ability to `resume` workerpool
- Added ability to `enqueue` tasks into the pool/queue seperate to worker
- Added tests for all added functionality

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks Jordan for your PR! 

Can you explain what `enqueue` does exactly? Isn't it possible to use the existing API `pool.exec` which can keep tasks in the queue when the pool is paused?

These new methods add bloat to the API of pool. That can be worth it, but it's good to think critically what the added value is and whether this is serving a generic or a very specific use case. A thought: Would it be possible to use composition here instead of extending `Pool`? It may be possible to create this pauseable queue as a wrapper around the workerpool.

**Comment by JPig** [comment]
in regards to `enqueue` I guess it's just in my eyes a helper function in the case of needing to batch add multiple tasks to the workerpool, It just makes it a bit nicer than a loop of multiple function calls etc. Im not really in any way tied to this part of the functionality though.

And in regards to the added `pause`/`resume` and `autoStart` functionality that was more for a utility to make the library more testable, just the ability to have a bit more fine grained control over what happens when.

And in terms of the composition thought, do you mean the like refactor the PR and the wrapper would be inside of this package/library as say an alternate class that can be used?, or are you suggesting to just add said functionality within the code of where its being implemented etc?

**Comment by josdejong** [comment]
Thanks for the clarification Jordan 👍 . Again, I'm trying to find a good balance between a simple, non-bloated API, and useful functionality.

I have the feeling that the `enqueue` method adds quite some code and relatively little added value. Unless I'm overlooking something I would think you can achieve the same with this helper function:

```js
function enqueue (pool, tasks) {
  tasks.forEach(task => pool.exec(task.method, task.params) 
}
``` 

I think there could be value in adding a _pause_ functionality, but I would like to have a stronger case before integrating it. I understand it can make testing easier, but without real world examples of needing this for real in an _application_ I would like to put this feature on hold. 

On a side note, what I'm a bit afraid of is that when implementing "pause", the expectation of users will be that tasks are _really_ paused. However, as you clearly explain in the docs, the pausing only prevents starting new tasks, but cannot pause currently running tasks. Depending on real-world use cases this may be fine or turn out to be a non-useful solution in practice.

What do you think?

**Comment by josdejong** [comment]
@JPig what do you think? Shall we close this PR?

**Comment by JPig** [comment]
> @JPig what do you think? Shall we close this PR?

Hey sorry for the slow reply, yep that is fine with me.

**Comment by josdejong** [comment]
:+1: thanks for your input and efforts!

**Pull request closed without merging**
