### PR TITLE
[Fixes #58] Allocate Debug ports safely, so multiple pools don’t acci…

### PR DESCRIPTION
**Pull request by stefanpenner**
…dentally overlap

### CODE REVIEW

**Comment by josdejong** [comment]
Wow, didn't think about that but indeed both pools try to use the same port.0

 I do like your approach of a central place to get a free port number, that makes sense. 

It may interesting too think about not keeping state in the `DebugPortAllocator` and find a free port by simply trying a range, though I'm not sure about the performance but when this is just about debugging that could be perfectly acceptable. Keeping state and having to release a port afterwards is more fragile than a dumb "just-try-until-you-find-something" approach. There are npm packages that can do this for us, like [get-port](https://www.npmjs.com/package/). How do you think about that @stefanpenner ?

**Comment by stefanpenner** [comment]
In ember-cli, we use https://www.npmjs.com/package/portfinder and we have contributed many fixes to that (turns out to be a harder problem than expected).

I don't mind adding that, I avoided doing as I wasn't sure if you wanted it as a dependency.

**Comment by josdejong** [comment]
> turns out to be a harder problem than expected

o really? Well, I don't think we should over-engineer this and add a large dependency just for this. In that case your current solution may be best and simplest after all.

**Comment by stefanpenner** [comment]
@josdejong I think its "ok" for now. How about if this problem in-practice arises for us we add portFinder?

The issues we had with portFinder are largely addressed, the tricky bits arose due to:

* mixing ipv4 and ipv6 interfaces
* some programs binding to 4 not 6 others to 6 not 4
* some programs, such as the MacBook Pro touch-bar running on a port, but leaving that port open...

**Comment by stefanpenner** [comment]
@josdejong I'm going to land this as-is, because the inability to debug builds is causing some grief.

I will though, gladly make any follow up changes :) Just let me know.

**Comment by stefanpenner** [comment]
updated `history.md` https://github.com/josdejong/workerpool/commit/9793e3e4596668a1f37fdd4ef87b811000f87edb

**Comment by stefanpenner** [comment]
Ah, I don't have NPM publish yet. Guess I can't actually ship this yet.

**Comment by josdejong** [comment]
> I think its "ok" for now. How about if this problem in-practice arises for us we add portFinder?

Yes I agree, no need to over think this right now.

I was also thinking, this functionality doesn't need to be bundled for use in the browser since it's only needed in node.js, maybe we can do something smart there.

**Comment by josdejong** [comment]
@stefanpenner shall I publish `v3.1.2` now?

**Comment by josdejong** [comment]
Will do a publish now @stefanpenner.

**Comment by stefanpenner** [comment]
@josdejong that would be wonderful :) Thank you kindly good sir.

**Comment by josdejong** [comment]
You're welcome :) I published v3.1.2 almost an hour ago, you should be able to use it.

**Pull request merged**
