### PR TITLE
fix: worker termination before it's ready

### PR DESCRIPTION
**Pull request by Michsior14**
Fixes the second issue mentioned in possible bugs thread (#387).

### CODE REVIEW

**Comment by josdejong** [comment]
Good find, thanks Michał!

TypeScript would have helped to prevent a bug like this I guess 🤔.

**Comment by josdejong** [comment]
Ready to merge?

**Comment by josdejong** [comment]
Your fix is published now in `v6.4.1`, thanks again!

**Comment by Michsior14** [comment]
> Good find, thanks Michał!
> 
> TypeScript would have helped to prevent a bug like this I guess 🤔.

Yeah, maybe I will find some time to continue what I started some time ago... but no promises :)

**Pull request merged**
