### PR TITLE
Add support for Yarn PnP

### PR DESCRIPTION
**Pull request by Turbo87**
[Yarn Plug'n'Play](https://github.com/yarnpkg/rfcs/pull/101) is using a custom resolver to lookup dependencies from a machine-wide global location, instead of keeping `node_modules` duplicated in every project.

When `yarn run` is used and it detects that it is running in PnP mode it will call the child process using `--require .pnp.js`, with `.pnp.js` being a file generated per-project by Yarn. This will enable PnP mode for the child process and make the PnP API available via `require('pnpapi')`.

Since `workerpool` is also forking off child processes it would need a similar mechanism to ensure that those child processes are able to resolve their dependencies correctly. This PR adds the necessary `--require` argument to the fork option if PnP mode is detected by checking `process.versions.pnp`.

In case you're wondering: we're working on making [`ember-cli`](https://github.com/ember-cli/ember-cli) compatible with Yarn PnP and that is using [`broccoli-babel-transpiler`](https://github.com/babel/broccoli-babel-transpiler), which is using `workerpool` under the hood.

/cc @arcanis @rwjblue

### CODE REVIEW

**Comment by rwjblue** [comment]
Chatted with @turbo87 in DM, I think we should move to inheriting `NODE_OPTIONS` instead (I’m somewhat surprised we aren’t already inheriting all of `process.env`).

This change would essentially be following the same move in Yarn itself (away from using `—require` to specifying `NODE_OPTIONS`) in https://github.com/yarnpkg/yarn/pull/6629.

**Comment by rwjblue** [comment]
Ah, apparently `child_process.fork` does not automatically inherit the current processes `process.env` ( `child_process.spawn` has this behavior). That explains why it doesn’t “just work”. 

See here for the two implementations (on Node 10):

* spawn -
https://github.com/nodejs/node/blob/1ae0511b942c01c6e0adff98643d350a395bf101/lib/child_process.js#L398-L552
* fork -
https://github.com/nodejs/node/blob/1ae0511b942c01c6e0adff98643d350a395bf101/lib/child_process.js#L61-L114

So the question here is, should we inherit all of `process.env` or only `process.env.NODE_OPTIONS`?

**Comment by Turbo87** [comment]
@rwjblue unfortunately, it's not quite as easy. `fork()` uses `spawn()` under the hood and that correctly forwards the existing env vars. but in our case when Yarn PnP mode is enabled via `ember` instead of using `yarn run` it will not have a `NODE_OPTIONS` env var with the correct value.

**Comment by Turbo87** [comment]
we will most likely resolve this another way (adjusting `NODE_OPTIONS` ourselves once we detect Yarn PnP mode) so I'll close this PR for now. sorry for the noise 😉

**Comment by josdejong** [comment]
:+1: thanks anyway Tobias for taking the time to put together a PR :)

**Pull request closed without merging**
